# Generated by Django 3.1.5 on 2021-03-30 17:20

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
